<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html xmlns="http://www.w3.org/1999/xhtml"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /><title>Steeplejack Company - Nationwide Steeplejack Services</title><meta name="description" content="Inspired Heights is a Christian steeplejack company" /><link href="design/style.css" rel="stylesheet" type="text/css" /><script type="text/javascript" src="js/fade.js"></script></head><body><div id="wrapper">	<div id="header">		<div class="phone"></div>		<div class="logo"><a href="/" title="Inspired Heights"><img src="images/logo.png" width="270" height="50" border="0" alt="Inspired Heights" /></a></div>	</div>	<div id="nav">		<div class="navigation_menu">			<div class="navigation_tcat"></div>			<ul class="menu">				<li><a href="index.php" class="menu_home" title="Home"></a></li>				<li><a href="about.php" class="menu_abou" title="About Us"></a></li>				<li><a href="church-steeples.php" class="menu_cste" title="Church Steeples"></a></li>				<li><a href="church-roofs.php" class="menu_croo" title="Church Roofs"></a></li>				<li><a href="mason_stone-restoration.php" class="menu_mres" title="Mason/Stone Restoration"></a></li>				<li><a href="church-windows.php" class="menu_cwin" title="Church Windows"></a></li>				<li><a href="church-interiors.php" class="menu_cint" title="Church Interiors"></a></li>				<li><a href="mentorship-program.php" class="menu_mpro" title="Mentorship Program"></a></li>			</ul>		</div>		<div class="display"><script type="text/javascript" language="javascript">new fadeshow(fadeimages, 693, 299, 0, 3000, 0);</script></div>		<div class="clear"></div>	</div>	<div id="titlebar">		<h1>About Inspired Heights</h1>		<div class="contact_button"><a href="contact.php" title="Contact Us"></a></div>		<!-- <div class="portfolio_button"><a href="#" title="Project Portfolio"></a></div> -->		<div class="clear"></div>	</div>	<div id="page">		<div class="page_top"></div>			<div class="page_main">				<div class="page_wrap">										<div class="float_right"><img src="images/chicago_steeple_repair.jpg" border="0" alt="Chicago Steeple Repair" /></div>
					<h1>Our Mission</h1>
					<p>Inspired Heights exists for the sole purpose of bringing glory to our Lord and Savior Jesus Christ through the maintenance, repair, and restoration of His Church.</p>
					<h1>What We Do</h1>
					<p>Inspired Heights combines the techniques of the past with the technology of today. This allows us to offer a less intrusive, more affordable, restoration of the highest quality.</p>
					<h1>Our History</h1>
					<p>As a third generation steeplejack, Tony Stratton learned to combine the best of old fashioned craftsmanship with current technical advances. Of the various types of construction Tony experienced as a steeplejack he most enjoyed churches. The history, architecture, and artistic detail always fascinated Tony while giving him the opportunity to serve the church he loves.</p>

<p>For this reason in 1993 Tony started his own steeplejack company that would specialize in the restoration and preservation of churches. Over the years Tony continued to expand through continual training and building of a diversified team. Originally called Tony Stratton-Steeplejack this company has grown to become Inspired Heights, Inc. a leader in church restoration.</p>

<p><em>He has shown us kindness... He has granted us new life to rebuild the house of our God and repair its ruins -- EZR 9:9b</em></p>
<h1>Please Post Any Recommendations Below</h1>

<a href="http://www.manta.com/c/mm391ld/inspired-heights#widget:recommendations;w:600;h:250;emid:mm391ld">Inspired Heights</a> <script src="http://www.manta.com/js/widget_embed.js"></script>

					<div class="clear"></div>				</div>			</div>		<div class="page_bot"></div>	</div>	<div id="footer">		<div class="botlinks"></div>		<div class="copyright">			All content copyright <strong>Inspired Heights, Inc.</strong>		</div>		<div class="clear"></div>	</div></div></body></html>