<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html xmlns="http://www.w3.org/1999/xhtml"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /><title>Church Roofs - Installation & Repair of Church Roofs</title><meta name="description" content="Church roofing contractor, church roof installation, church roof repair" /><link href="design/style.css" rel="stylesheet" type="text/css" /><script type="text/javascript" src="js/fade.js"></script></head><body><div id="wrapper">	<div id="header">		<div class="phone"></div>		<div class="logo"><a href="/" title="Inspired Heights"><img src="images/logo.png" width="270" height="50" border="0" alt="Inspired Heights" /></a></div>	</div>	<div id="nav">		<div class="navigation_menu">			<div class="navigation_tcat"></div>			<ul class="menu">				<li><a href="index.php" class="menu_home" title="Home"></a></li>				<li><a href="about.php" class="menu_abou" title="About Us"></a></li>				<li><a href="church-steeples.php" class="menu_cste" title="Church Steeples"></a></li>				<li><a href="church-roofs.php" class="menu_croo" title="Church Roofs"></a></li>				<li><a href="mason_stone-restoration.php" class="menu_mres" title="Mason/Stone Restoration"></a></li>				<li><a href="church-windows.php" class="menu_cwin" title="Church Windows"></a></li>				<li><a href="church-interiors.php" class="menu_cint" title="Church Interiors"></a></li>				<li><a href="mentorship-program.php" class="menu_mpro" title="Mentorship Program"></a></li>			</ul>		</div>		<div class="display"><script type="text/javascript" language="javascript">new fadeshow(fadeimages, 693, 299, 0, 3000, 0);</script></div>		<div class="clear"></div>	</div>	<div id="titlebar">		<h1>Church Roofing Contractor - Church Roofs</h1>		<div class="contact_button"><a href="contact.php" title="Contact Us"></a></div>		<!-- <div class="portfolio_button"><a href="#" title="Project Portfolio"></a></div> -->		<div class="clear"></div>	</div>	<div id="page">		<div class="page_top"></div>			<div class="page_main">				<div class="page_wrap">										<div class="float_right"><img src="images/Church_Roofing.jpg" border="0" alt="Church Roof Installation" /></div>
					<p>Church roofs can vary immensely from one church to another, but they are much more than aesthetics. A properly installed roof can protect your church for decades, even centuries.</p>
<p>Inspired Heights is a licensed commercial roofing contractor with experience in the traditional building materials that are common to church roofs (slate, cedar, tile, copper, etc.).</p>
<p>In addition to conventional roofing materials, Inspired Heights stays current with new roofing products as they become available (50 year asphalt / fiberglass shingles, cedar breather, synthetic slate, laminated metal shingles, etc).</p>
					<p><em>So he built the temple and completed it, roofing it with beams and cedar planks.-- 1 King 6:9</em></p>
<p>Inspired Heights, Inc is a company that specializes in church roof installation and church roof repair. Our diversified experience working with a variety of materials on church roofs allows us to offer a selection that would be right for your church roof project. Inspired Heights, your church roof specialists! </p>
<p><big><b>New Church Roof Installation</b></big></p>
<p>Church roofs are not your standard roof and their repairs and installation can be very complex involving steeples, concealed gutters and parapets. Furthermore, the traditional building materials often found on church roofs present unique problems that require specialized training. When your church contemplates the roofing materials available there are several factors to consider.</p>
<p>The first of which is cost. Not just the immediate, but also what can be expected over the life of the church roof. A new church roof can be a sizable investment for your church and should be made wisely. The money saved by hiring a cut rate roofer can be regretted for years to come, often being lost in needless repairs. In contrast the extra money associated with quality roofing products and an experienced church roofer can pay for itself in the extra life expectancy of the new church roof.</p>
<p>Another factor to consider when searching for the right shingle for your church roof is aesthetics. For historical preservation many churches may find it difficult to change the appearance of the church roof. Therefore, a roofing company that is familair with both the traditional materials used and their modern counterparts could be very beneficial for your church roof project.</p>
<p>A final consideration when looking for a church roofing company is the installer's experience and reputation with the type of roof and materials to be used. Not all roofs are equal and each has its unique method of installation.</p>
<p><big><b>Church Roof Maintenance</b></big></p>
<p>Careful observations of the church roof and church gutters can detect many potential problems before they become a threat to the church. Some warning signs include discoloration or dirty streaks appearing on the interior or exterior church walls, especially close to the top. This may denote a leaking or overflowing gutter. Look for dislocated and broken slates and tiles; denoting nail deterioration or storm damage. Sections of the church roof may not be visible from the ground and will require greater diligence in detecting problems during their early stages and should be done by a roofing professional with experience in the specific materials on your church roof. At the first sign of a problem a church roof specialist should be contacted. Seek the council of a roofing company who has a broader understanding of the interrelation between the church roof, steeple, gutters and the remaining parts of the church building. Proper maintenance and inspection of your church roof is paramount to its longevity and should therefore be regularly scheduled, a little prevention can spare the church costly repairs latter.</p>
<p><big><b>Know Your Church Roof</b></big></p>
<p>The basic purpose of the church roof is to keep the weather out. This exposes the church roof to the harshest of the elements. The church roof is subject to the worst our climate can bring against it; 365 days a year of unrelenting rain, snow, wind and the beating sun. The church roof and steeples are usually the most vulnerable areas of the church building and must be properly maintained to preserve its weatherproof properties.</p>
<p>The following information is intended to help you understand the very basics of your church roof. Church roofs generally fall in to one of two categories.</p>
<p>Water-shedding Roofs: Normally installed on steep pitched church roofs to ensure the water runs off the church roof and into the church gutters. They include slate, tile, cedar shakes, clay or concrete, metal shingles and your typical asphalt shingle. These shingles / tiles themselves may be waterproof, often interlocking and sealing together, but the water shedding church roof is not. Therefore, the proper maintenance, repair and replacement of damaged or missing shingles is crucial to the church roof’s ability to redirect and deflect the water into the church gutter system. With proper care a slate church roof has a life expectancy of 100 plus years.</p>
<p>Water-proof Roofs: Usually installed to low pitched “flat” roofs include soldered metal roofs, (lead, stainless steel and copper) asphalt, roofing felt and roofing membranes. The water-proof church roof is susceptible to leaks caused by standing water and therefore must be carefully pitched for proper drainage and remain sealed to maintain its water proof integrity. A properly maintained metal church roof can have a life expectancy equivalent to slate (100 plus years) while cheaper roofing materials may have less than a 15 year expectancy.</p>
<p>We are a nationwide church roofing contractor that offers installation and repair of church roofs and church steeples in Alabama, Alaska, Arizona, Arkansas, California, Colorado, Connecticut, Delaware, Florida, Georgia, Hawaii, Idaho, Illinois, Indiana, Iowa, Kansas, Kentucky, Louisiana, Maine, Maryland, Massachusetts, Michigan, Minnesota, Mississippi, Missouri, Montana, Nebraska, Nevada, New Hampshire, New Jersey, New Mexico, New York, North Carolina, North Dakota, Ohio, Oklahoma, Oregon, Pennsylvania, Rhode Island, South Carolina, South Dakota, Tennessee, Texas, Utah, Vermont, Virginia, Washington, West Virginia, Wisconsin, Wyoming. Including the cities of New York, NY - Los Angeles, CA - Chicago, IL - Houston, TX - Philadelphia, PA - San Diego, CA - Detroit, MI - Dallas, TX - Phoenix, AZ - San Antonio, TX - San Jose, CA - Baltimore, MD - Indianapolis, IN - San Francisco, CA - Jacksonville, FL - Columbus, OH - Milwaukee, WI - Memphis, TN - Washington, DC - Boston, MA - Seattle, WA - St. Louis, MO - Atlanta, GA - Pittsburgh, PA - Minneapolis, MN - Miami, FL - Tampa, FL</p>
					<div class="clear"></div>				</div>			</div>		<div class="page_bot"></div>	</div>	<div id="footer">		<div class="botlinks"></div>		<div class="copyright">			All content copyright <strong>Inspired Heights, Inc.</strong>		</div>		<div class="clear"></div>	</div></div></body></html>