<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html xmlns="http://www.w3.org/1999/xhtml"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /><title>Church Steeples - Repair & Restoration of Church Steeples. Steeplejack Services</title><meta name="description" content="Inspired Heights is a steeplejack company that specializes in church steeples." /><link href="design/style.css" rel="stylesheet" type="text/css" /><script type="text/javascript" src="js/fade.js"></script></head><body><div id="wrapper">	<div id="header">		<div class="phone"></div>		<div class="logo"><a href="/" title="Inspired Heights"><img src="images/logo.png" width="270" height="50" border="0" alt="Inspired Heights" /></a></div>	</div>	<div id="nav">		<div class="navigation_menu">			<div class="navigation_tcat"></div>			<ul class="menu">				<li><a href="index.php" class="menu_home" title="Home"></a></li>				<li><a href="about.php" class="menu_abou" title="About Us"></a></li>				<li><a href="church-steeples.php" class="menu_cste" title="Church Steeples"></a></li>				<li><a href="church-roofs.php" class="menu_croo" title="Church Roofs"></a></li>				<li><a href="mason_stone-restoration.php" class="menu_mres" title="Mason/Stone Restoration"></a></li>				<li><a href="church-windows.php" class="menu_cwin" title="Church Windows"></a></li>				<li><a href="church-interiors.php" class="menu_cint" title="Church Interiors"></a></li>				<li><a href="mentorship-program.php" class="menu_mpro" title="Mentorship Program"></a></li>			</ul>		</div>		<div class="display"><script type="text/javascript" language="javascript">new fadeshow(fadeimages, 693, 299, 0, 3000, 0);</script></div>		<div class="clear"></div>	</div>	<div id="titlebar">		<h1>Steeplejack Services - Church Steeple Repair and Restoration</h1>		<div class="contact_button"><a href="contact.php" title="Contact Us"></a></div>		<!-- <div class="portfolio_button"><a href="#" title="Project Portfolio"></a></div> -->		<div class="clear"></div>	</div>	<div id="page">		<div class="page_top"></div>			<div class="page_main">				<div class="page_wrap">										<div class="float_right"><img src="images/Steeplejacks.jpg" border="0" alt="Steeplejacks on Church Steeple" /></div>
					<p>Though beautiful testaments to the neighborhood, church steeples, towers, finials and spires are often neglected due to the unique problems they pose for the average contractor. As a steeplejack company our trained professionals are able to maintain, repair and restore your church steeple with the hands on approach that only a steeplejack could offer. In addition, the steeplejack services we provide allow us access to your church steeple without the high cost associated with modern techniques (cranes, scaffold). </p>
					<p>These services include:</p>
					<ul>
						<li>Steeple Painting</li>
                                                                                                                                <li>Steeple Repairs</li>
						<li>Tuck point and stone / mason restoration</li>
						<li>Steeple Roof (cedar, metal, asphalt and slate steeple)</li>
						<li>lightning protection</li>
					</ul>
					<p>Inspired Heights are your steeple restoration specialists!</p>
					<p><em>And they said, Let us rise up and build. So they strengthened their hands for this good work. -- NEH 2:18b</em></p>
<p><big><b>Inspired Heights - Church Steeple Contractors</b></big></p>
<p>Inspired Heights, Inc is a national steeplejack company that specializes in church steeple repair. The company president, Tony Stratton, is a third generation steeplejack experienced in church steeple maintenance, repair and restoration.</p>
<p>The comprehensive steeplejack services Inspired Heights perform on church steeples include: steeple repairs, steeple painting, steeple tuck pointing, steeple stone & mason restoration, Steeple Roofs (cedar, metal, asphalt / fiberglass and slate steeple), lightning protection and etc. In addition to church steeple repair our steeplejack services include church towers and church spires.
Our steeplejack methods offer affordable solutions to all the highwork that is often associated with interior and exterior church repair and restoration. These techniques can be used on the high sanctuary / nave ceilings, difficult church windows, high soffits and etc.</p>
<p><big><b>Church steeple repair, maintenance and restoration</b></big></p> 
<p>The church steeple is a focal point of many churches, a witness to the neighborhood and an architectural design intended to lift one’s eye’s upwards, as towards heaven. Nonetheless, the church steeple is often neglected due to its precarious location and the engineered treasure falls into disarray and does not receive the church steeple repairs it requires.</p>
<p>Church steeples, spires, towers and finials have dotted the skyline for centuries and yet church steeple repair still perplexes countless churches and confounds many contractors, perhaps now more than ever. The basis of this turmoil is the inaccessibility of the church steeple coupled with a dwindling number of artisans who specialize in the unique work of church steeple repair and restoration.</p>
<p>For centuries the specialized work of church steeple repair was performed by steeplejacks; a master rigger who’s unique training gave them complete access to even the tallest of church steeples. To provide the numerous services that would be labeled as steeple repair the steeplejack has to be experienced church roofers, church painters, carpenters, sheet metal workers and church masons to facilitate the various needs of the many styles of church steeples.</p>
<p>Today’s contractor attempting modern approaches to church steeple repair would use scaffolding and cranes. These techniques are typically more intrusive and much more costly than the methods of the traditional steeplejack. In addition the steeplejack can offer a “hands on” church steeple repair that the common contractor could never duplicate.</p>
<p><big><b>Steeplejack Services</b></big></p>
<p>Inspired Heights is a steeplejack company specialized in church steeple repair. Our steeplejack services are offered around the country. Tony Stratton, the company’s president, is a third generation steeplejack who is experienced in church steeple maintenance, repair and restoration. In addition, the steeplejack services offered by Inspired Heights can provide complete affordable solutions to your church's interior and exterior church repair and restoration.</p> 
<p><big><b>What is a Steeplejack?</b></big></p>
<p>A steeplejack is “a person whose work is building smokestacks, towers, or steeples or climbing up the outside of such structures to paint and make repairs.” merriam-webster. The compound word steeple-jack is comprised of the two words steeple and jack. Steeple clearly defining the location and jack, often meaning a man, laborer or a sailor. Though the first known use of the word steeplejack dates back to 1852 the techniques are centuries old. It is believed that the sailors of the tall sailing ships are the original steeplejacks. They would come to port and during their time ashore they would use their rigging skills to climb and repair church steeples. While over the centuries many of the tools and safety apparatuses of the steeplejack may have changed, the basic technique still remains the same. A bosun’s chair suspended from a block and tackle pulley system allows the steeplejack complete access to the church steeple. Sometimes the steeplejack would strap ladders or install a temporary “crow’s nest” to act as a work platform. The steeplejack needs to be more than a master rigger; the steeplejack would need to be proficient in the various repairs needed for steeple restoration. These would often include several types of roofs (repairs and installation), carpentry, tuck pointing, sheet metal work, painting and etc. The steeplejack’s methods are still used today under carefully adhered to OSHA regulations and can often save a church hundreds of thousands of dollars in their church and steeple restoration project. Yet, this is not the only benefit the steeplejack has over the high work alternatives (expensive cranes and scaffolds). The steeplejack is able to offer a hands-on, up close approach that other tradesmen could never duplicate, permitting the steeplejack to provide a superior service at a fraction of the price!<p>
<p>We are a nationwide steeplejack company that offers church and church steeple maintenance, repair and restoration services in Alabama, Alaska, Arizona, Arkansas, California, Colorado, Connecticut, Delaware, Florida, Georgia, Hawaii, Idaho, Illinois, Indiana, Iowa, Kansas, Kentucky, Louisiana, Maine, Maryland, Massachusetts, Michigan, Minnesota, Mississippi, Missouri, Montana, Nebraska, Nevada, New Hampshire, New Jersey, New Mexico, New York, North Carolina, North Dakota, Ohio, Oklahoma, Oregon, Pennsylvania, Rhode Island, South Carolina, South Dakota, Tennessee, Texas, Utah, Vermont, Virginia, Washington, West Virginia, Wisconsin, Wyoming. Including the cities of New York, NY - Los Angeles, CA - Chicago, IL - Houston, TX - Philadelphia, PA - San Diego, CA - Detroit, MI - Dallas, TX - Phoenix, AZ - San Antonio, TX - San Jose, CA - Baltimore, MD - Indianapolis, IN - San Francisco, CA - Jacksonville, FL - Columbus, OH - Milwaukee, WI - Memphis, TN - Washington, DC - Boston, MA - Seattle, WA - St. Louis, MO - Atlanta, GA - Pittsburgh, PA - Minneapolis, MN - Miami, FL - Tampa, FL</p>
					<div class="clear"></div>				</div>			</div>		<div class="page_bot"></div>	</div>	<div id="footer">		<div class="botlinks"></div>		<div class="copyright">			All content copyright <strong>Inspired Heights, Inc.</strong>		</div>		<div class="clear"></div>	</div></div></body></html>