<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html xmlns="http://www.w3.org/1999/xhtml"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /><title>Church Renovation - Restoration and Renovations of Church Interiors</title><meta name="description" content="Inspired Heights renovates and restores church interiors" /><link href="design/style.css" rel="stylesheet" type="text/css" /><script type="text/javascript" src="js/fade.js"></script></head><body><div id="wrapper">	<div id="header">		<div class="phone"></div>		<div class="logo"><a href="/" title="Inspired Heights"><img src="images/logo.png" width="270" height="50" border="0" alt="Inspired Heights" /></a></div>	</div>	<div id="nav">		<div class="navigation_menu">			<div class="navigation_tcat"></div>			<ul class="menu">				<li><a href="index.php" class="menu_home" title="Home"></a></li>				<li><a href="about.php" class="menu_abou" title="About Us"></a></li>				<li><a href="church-steeples.php" class="menu_cste" title="Church Steeples"></a></li>				<li><a href="church-roofs.php" class="menu_croo" title="Church Roofs"></a></li>				<li><a href="mason_stone-restoration.php" class="menu_mres" title="Mason/Stone Restoration"></a></li>				<li><a href="church-windows.php" class="menu_cwin" title="Church Windows"></a></li>				<li><a href="church-interiors.php" class="menu_cint" title="Church Interiors"></a></li>				<li><a href="mentorship-program.php" class="menu_mpro" title="Mentorship Program"></a></li>			</ul>		</div>		<div class="display"><script type="text/javascript" language="javascript">new fadeshow(fadeimages, 693, 299, 0, 3000, 0);</script></div>		<div class="clear"></div>	</div>	<div id="titlebar">		<h1>Interior Church Renovations</h1>		<div class="contact_button"><a href="contact.php" title="Contact Us"></a></div>		<!-- <div class="portfolio_button"><a href="#" title="Project Portfolio"></a></div> -->		<div class="clear"></div>	</div>	<div id="page">		<div class="page_top"></div>			<div class="page_main">				<div class="page_wrap">					<div class="float_right"><img src="images/church_interiors.jpg" border="0" alt="Interior Church Renovations" /></div>
<p>The church sanctuary or nave is the place we gather and worship our Lord. For this reason the entire environment is designed to inspire awe. This may be accomplished through high ceilings, gold leafing, murals and icons. These artistic expressions of faith work together with the practical needs of the modern church to create a worship experience.</p>
<p>Inspired Heights can help you with your interior church renovation project.</p>
<ul>
	<li>Wall & Ceiling Painting</li><li>Gold leafing & Stenciling</li><li>Iconic & Liturgical Art</li><li>Gilding</li><li>Wood refinishing</li><li>Plaster Repair</li><li>Carpentry</li><li>Pew restoration & upholstery</li><li>Altars</li><li>Pulpits</li><li>Lighting &amp; sound systems</li><li>And more...</li>
</ul>
<p><em>And let them make me a sanctuary; that I may dwell among them. -- Exodus 25:8</em></p>
<p> Remoldeling, renovating and restoring church interiors offer unique challenges that most interior church painters could not perform. Inspired Heights are the experienced professionals and artisans your church needs for your church’s renovation and interior church restoration project. We set the highest standards for your church's interior maintenance, repair and restoration project. </p>
<p> The highwork techniques we offer at Inspired Heights can allow us to typically perform your interior church restoration project with little or no disruption to services. </p>
<p> Plaster Repair: A lasting quality paint job for your church’s interior painting project is dependent upon the plaster repair and prep work that form the foundation. Therefore, your church’s plaster repairs should be performed by experienced craftsman. Loose plaster from your church’s walls and ceilings must be either re-secured or removed to provide a solid foundation for your church’s new plaster. Cracks in your church’s plaster need to be dug out and properly filled; surface patching and skim coatings may be unsightly, less durable and therefore not recommended for your church painting, plaster and renovation project. Elastomeric plaster and finish coats provide a durable finish that is more tolerant to the slight movements that are typically a major contributor to cracks in the church plaster. New plaster should always be primed prior to painting.</p>
<p> Selecting Your Paint: Always select quality paint! Inexpensive paints are never worth the price you pay. Inspired Heights always chose high-quality paints that provide better coverage and last longer. Painting contractor who go with a lower-quality paint based solely on the price tag will probably end up costing the church more money in the long run because you’ll have to apply more coats and repaint sooner. <p/>
<p> While selecting the colors for your church’s painting project is usually a matter of aesthetics the right sheen is vital to the finished look and should be carefully selected based upon the texture, traffic and lighting. Inspired Heights can help your church select the right paints for your church’s interior renovation project. </p>
<p> Liturgical Art: Liturgical and iconic art is art consecrated in service to God and His Church. More accurately it is Sacred Art, set apart for the honor and glory of God. Because of its sacramental character liturgical art has the ability to engage our spirit and soul while connecting us to our Creator. Liturgical Art is an expression of Faith and inspires Faith. </p>
<p>Because of the spiritual nature, the liturgical artists of Inspired Heights treats your church’s liturgical art project as we do all our work… as an act of worship.</p>
<p> Our Church Interior Services include: painting church ceilings and walls, gold leaf and stenciling, iconic and liturgical art, gilding, wood refinishing, plaster repair, carpentry, pew restoration and upholstery, altars, pulpits, lighting and sound systems, etc.</p>
<p>We are a nationwide painting contractor that specializes in interior church renovation and restoration. Providing our specialized services in Alabama, Alaska, Arizona, Arkansas, California, Colorado, Connecticut, Delaware, Florida, Georgia, Hawaii, Idaho, Illinois, Indiana, Iowa, Kansas, Kentucky, Louisiana, Maine, Maryland, Massachusetts, Michigan, Minnesota, Mississippi, Missouri, Montana, Nebraska, Nevada, New Hampshire, New Jersey, New Mexico, New York, North Carolina, North Dakota, Ohio, Oklahoma, Oregon, Pennsylvania, Rhode Island, South Carolina, South Dakota, Tennessee, Texas, Utah, Vermont, Virginia, Washington, West Virginia, Wisconsin, Wyoming. Including the cities of New York, NY - Los Angeles, CA - Chicago, IL - Houston, TX - Philadelphia, PA - San Diego, CA - Detroit, MI - Dallas, TX - Phoenix, AZ - San Antonio, TX - San Jose, CA - Baltimore, MD - Indianapolis, IN - San Francisco, CA - Jacksonville, FL - Columbus, OH - Milwaukee, WI - Memphis, TN - Washington, DC - Boston, MA - Seattle, WA - St. Louis, MO - Atlanta, GA - Pittsburgh, PA - Minneapolis, MN - Miami, FL - Tampa, FL</p>
					<div class="clear"></div>				</div>			</div>		<div class="page_bot"></div>	</div>	<div id="footer">		<div class="botlinks"></div>		<div class="copyright">			All content copyright <strong>Inspired Heights, Inc.</strong>		</div>		<div class="clear"></div>	</div></div></body></html>