<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html xmlns="http://www.w3.org/1999/xhtml"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /><title>Church Windows - Repair & Restoration of Church Windows</title><meta name="description" content="Inspired Heights repairs and restores church windows and stained glass" /><link href="design/style.css" rel="stylesheet" type="text/css" /><script type="text/javascript" src="js/fade.js"></script></head><body><div id="wrapper">	<div id="header">		<div class="phone"></div>		<div class="logo"><a href="/" title="Inspired Heights"><img src="images/logo.png" width="270" height="50" border="0" alt="Inspired Heights" /></a></div>	</div>	<div id="nav">		<div class="navigation_menu">			<div class="navigation_tcat"></div>			<ul class="menu">				<li><a href="index.php" class="menu_home" title="Home"></a></li>				<li><a href="about.php" class="menu_abou" title="About Us"></a></li>				<li><a href="church-steeples.php" class="menu_cste" title="Church Steeples"></a></li>				<li><a href="church-roofs.php" class="menu_croo" title="Church Roofs"></a></li>				<li><a href="mason_stone-restoration.php" class="menu_mres" title="Mason/Stone Restoration"></a></li>				<li><a href="church-windows.php" class="menu_cwin" title="Church Windows"></a></li>				<li><a href="church-interiors.php" class="menu_cint" title="Church Interiors"></a></li>				<li><a href="mentorship-program.php" class="menu_mpro" title="Mentorship Program"></a></li>			</ul>		</div>		<div class="display"><script type="text/javascript" language="javascript">new fadeshow(fadeimages, 693, 299, 0, 3000, 0);</script></div>		<div class="clear"></div>	</div>	<div id="titlebar">		<h1>Church Windows - Painting, Repair & Restoration</h1>		<div class="contact_button"><a href="contact.php" title="Contact Us"></a></div>		<!-- <div class="portfolio_button"><a href="#" title="Project Portfolio"></a></div> -->		<div class="clear"></div>	</div>	<div id="page">		<div class="page_top"></div>			<div class="page_main">				<div class="page_wrap">					<div class="float_right"><img src="images/church_window_repair.jpg" border="0" alt="Church Window Repair - Painting" /></div>
<p>The church window often combines function with the proclamation of our faith. Stained glass and painted glass windows are beautiful pieces of art that are considered standards in traditional churches but they require specialized care.</p>
<p>The craftsmen of Inspired Heights can maintain your church windows through glazing, painting, glass replacement, etc.</p>
<p>Using new restoration products we are also capable of restoring your deteriorated church windows that were once considered irreparable.</p>
<p>We also offer a hidden storm window system that insulates the church and protects the stained glass window.</p>
<p><em>And it came to pass... that he began to build the house of the LORD. And for the house he made windows of narrow lights. -- 1 Kings 6:1, 4</em></p>
<p>No matter what kind of windows your church window repair job includes, we have the solution for you. Our experience speaks for itself when it comes to church window repair. We have worked with many churches on stained glass, circular, extremely large, steeple windows, and many other kinds of church windows as well. Please give Inspired Heights a call today for a free estimate and consultation on our church window repair service.</p>
<p><big><b>Maintenance of Church Windows and Stained Glass</b></big></p>
<p>Church windows are often classic examples of ecclesiastical art meeting function. The church windows can feature different styles, techniques and subject matter causing every church window to be unique. Therefore, their maintenance and preservation should be entrusted only to skilled artisans who are experienced in church windows. The church window is one of the most at risk features of a church building. Any maintenance or repair should be based on a thorough knowledge of church windows and an awareness of their typical problems. The craftsman must understand the components of, and the dangers to, the church window. Each is essential to the window’s durability and damage to one part can cause the failure of the whole church window.</p>
<p>The primary component of the church window is the glass, which can be undecorated, colored, stained, painted, enameled, etched and of a range of textures. Hand-made antique glass has a unique quality and is unlike modern machined glass. For this reason, replacement of old glass should be done sparingly. Paint and surface decorations give the church window its narrative and constitute the most vulnerable part of the window. The glass-paint and enamels are applied to the inside of the glass pane and a yellow stain to the exterior. The glass is then fired to fuse them permanently to the glass. The durability of the church window’s design may fluctuate according to the firing. Though painted or stained glass windows are considered the “traditional” church window, historic undecorated glass can be an equally valuable contribution to the church. Due to the several types of glass and decorating techniques the preservation of historic church windows and their decorative surfaces should always be entrusted to a seasoned expert.</p>
<p>Glazing. Smaller historic / stained glass church windows are often held in place by the mortar in the glazing grooves while the larger church windows require additional support; usually in the form of a metal frame-work having the glazed panels fastened to the system by copper ties. The glazing mortar must be maintained to preserve the integrity of the stained glass church window. Lead strips (newer windows often use zinc) hold the pieces of glass together and, therefore, play a vital role in the church window. If the original leading fails and needs to be replaced it is important to match the original width and profile of the lead channels.</p>
<p><big><b>Some causes and signs of damage</b></big></p>
<p>Church windows are not only decorative but also form part of the external ‘skin' of the church building. Like all parts of the church, windows require regular maintenance and care. The church window is also affected by the condition of the whole building. For example, a water leak can cause the metal frame to rust and the associated expansion of the metal can break and stain the stone of the church window surround and endanger the glass panels. Likewise, the use of inappropriate mortar for the repair of church windows can cause severe damage to the surrounding stonework.
Damage can also be caused by structural defects, such as inadequate support, un-vented storm windows, failure of the lead or of the copper ties. The bulging or bowing of the window, cracking along the face of the lead and white, powdery stains are all signs of failing leading. Poorly-fired paint can lead to fragile pigments which can easily flake off. Regularly inspect the church windows for signs of paint loss. If you see signs of paint loss, instruct your church cleaners never to dust or wet-clean the window surfaces.</p>
<p>As part of the general inspection of the building look out for signs of leaks and water stains around the church windows in order to avoid serious damage. Any repairs or modifications to your church windows should be left to qualified craftsmen who are experienced in the unique properties of your church windows.</P>
<p><big><b>Storm Windows - Church Window Protection</b></big></p>
<p>There are typically 5 reasons that a church decides to install storm windows over the church windows.<p>
<p>1. Conserve heat. With the rising costs of heating a church this is the most common reason for installing storm windows. Nonetheless, in most churches the amount of heat lost through the church windows is relatively small (most goes through the roof) and ‘double glazing’ will not significantly reduce heat loss. Therefore, insulating the attic or installing an energy efficient furnace may be more effective and should be undertaken prior to installing storm windows.</p>
<p>2. Prevent drafts. A storm window system can be a helpful addition in reducing or eliminating drafts / noises caused by the wind. However, if members of the congregation complain about drafts coming from the church windows then checking / repairing the lead and window frames may be a likely solution and should be the first step to improving the situation.</p>
<p>3. Add weather protection. If the window leaks it should be repaired, since it is likely that the lead or pointing is in need of attention. A storm window system should not be installed to avoid necessary repairs. A repair that is delayed is usually a growing problem and is never a viable solution.</p>
<p>4. Prevent break-ins. Anyone intent on breaking into the church building will not be deterred by window protection. Tragically, alarm systems and heavy metal grilles are needed to protect against break-ins and have become normal features found within many churches.</p>
<p>5. Glass protection. Perhaps the best reason to install window protection is to protect the expensive and historic glass from weather damage and vandals. Church buildings are not exempt from vandalism and church windows are the most vulnerable target.</p>
<p><big><b>Storm Window Installation</b></big></p>
<p>The following criteria should be considered when fitting the church window protection:</p>
<p>• Windows should be fitted within the church window tracery and mullions.</p>
<p>• The storm window installation should allow their removal for the maintenance of the church windows.</p>
<p>• Wherever possible the fixings should avoid being screwed into the existing church windows.</p>
<p>• Polycarbonate and Plexiglas storm windows should be installed 2 inches away from the existing glass to allow them to deflect without damaging the church window.</p>
<p>• Glass window panes may be installed closer than 2 inches from the existing glass.</p>
<p>• Adequate ventilation should be provided between the existing glass and the storm window to enable air circulation and avoid condensation and possible bowing / damage to the existing church windows and leading.</p>
<p>We are a nationwide church window company that offers specialized maintenance, repair and restoration of church windows and stained glass in Alabama, Alaska, Arizona, Arkansas, California, Colorado, Connecticut, Delaware, Florida, Georgia, Hawaii, Idaho, Illinois, Indiana, Iowa, Kansas, Kentucky, Louisiana, Maine, Maryland, Massachusetts, Michigan, Minnesota, Mississippi, Missouri, Montana, Nebraska, Nevada, New Hampshire, New Jersey, New Mexico, New York, North Carolina, North Dakota, Ohio, Oklahoma, Oregon, Pennsylvania, Rhode Island, South Carolina, South Dakota, Tennessee, Texas, Utah, Vermont, Virginia, Washington, West Virginia, Wisconsin, Wyoming. Including the cities of New York, NY - Los Angeles, CA - Chicago, IL - Houston, TX - Philadelphia, PA - San Diego, CA - Detroit, MI - Dallas, TX - Phoenix, AZ - San Antonio, TX - San Jose, CA - Baltimore, MD - Indianapolis, IN - San Francisco, CA - Jacksonville, FL - Columbus, OH - Milwaukee, WI - Memphis, TN - Washington, DC - Boston, MA - Seattle, WA - St. Louis, MO - Atlanta, GA - Pittsburgh, PA - Minneapolis, MN - Miami, FL - Tampa, FL</p>
					<div class="clear"></div>				</div>			</div>		<div class="page_bot"></div>	</div>	<div id="footer">		<div class="botlinks"></div>		<div class="copyright">			All content copyright <strong>Inspired Heights, Inc.</strong>		</div>		<div class="clear"></div>	</div></div></body></html>