<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html xmlns="http://www.w3.org/1999/xhtml"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /><title>Church and Steeple Mason & Stone Restoration</title><meta name="description" content="Inspired Heights performs Church and steeple tuck pointing and stone restoration" /><link href="design/style.css" rel="stylesheet" type="text/css" /><script type="text/javascript" src="js/fade.js"></script></head><body><div id="wrapper">	<div id="header">		<div class="phone"></div>		<div class="logo"><a href="/" title="Inspired Heights"><img src="images/logo.png" width="270" height="50" border="0" alt="Inspired Heights" /></a></div>	</div>	<div id="nav">		<div class="navigation_menu">			<div class="navigation_tcat"></div>			<ul class="menu">				<li><a href="index.php" class="menu_home" title="Home"></a></li>				<li><a href="about.php" class="menu_abou" title="About Us"></a></li>				<li><a href="church-steeples.php" class="menu_cste" title="Church Steeples"></a></li>				<li><a href="church-roofs.php" class="menu_croo" title="Church Roofs"></a></li>				<li><a href="mason_stone-restoration.php" class="menu_mres" title="Mason/Stone Restoration"></a></li>				<li><a href="church-windows.php" class="menu_cwin" title="Church Windows"></a></li>				<li><a href="church-interiors.php" class="menu_cint" title="Church Interiors"></a></li>				<li><a href="mentorship-program.php" class="menu_mpro" title="Mentorship Program"></a></li>			</ul>		</div>		<div class="display"><script type="text/javascript" language="javascript">new fadeshow(fadeimages, 693, 299, 0, 3000, 0);</script></div>		<div class="clear"></div>	</div>	<div id="titlebar">		<h1>Church Mason &amp; Stone Restoration</h1>		<div class="contact_button"><a href="contact.php" title="Contact Us"></a></div>		<!-- <div class="portfolio_button"><a href="#" title="Project Portfolio"></a></div> -->		<div class="clear"></div>	</div>	<div id="page">		<div class="page_top"></div>			<div class="page_main">				<div class="page_wrap">										<div class="float_right"><img src="images/stone_restoration.jpg" border="0" alt="Church Mason Restoration" /></div>
					<p>Brick and stone are part of the unique characteristics of many churches and with the proper maintenance they can last hundreds of years. Church masonry and tuck pointing requires a proper understanding of the elements, historic materials, lime mortar mixes and new cementitious compounds that can permanently restore your sand stone / lime stone and other stonework.</p>
					<p>The professionals of Inspired Heights can meet all your church's stone and mason restoration needs.</p>
					<ul>
						<li>Tuck Pointing</li>
						<li>Brick Replacement</li>
						<li>Stone Restoration</li>
						<li>Stucco Repair</li>
						<li>And more...</li>
					</ul>
					<p><em>Work the clay, tread the mortar, repair the brickwork! -- Nahum 3:14b</em></p>
<p>The professionals of Inspired Heights can meet all your church stone & masonry maintenance needs. Church tuck pointing, church brick replacement, church stone restoration, stucco church repair, etc.</p>
<p><big><b>Traditional Church Masonry and Tuck Pointing</b></big></p>
<p>Over the years there have been many changes made in the masonry field. Therefore, careful considerations must be made whenever interacting with the traditional building materials that are often found on historic churches.</p>
<p>Historic Church Brick: Bricks are formed from clay mixed with sand and fired in a kiln. Bricks made during the historic period are typically softer than our modern bricks because today’s kilns fire bricks at a higher temperature, resulting in a consistently harder brick. Often the bricks used during the historic period would be locally fired using local materials, further affecting the brick’s consistency. These soft bricks were often used in the building of our historic churches. Because their composition is different, the treatment methods for modern bricks are incompatible with the soft bricks found on historic churches.</p>
<p>Historic Lime Mortar and Tuck Pointing: Mortar is a binding agent that also serves as the cushion in a masonry structure. Historic mortar is a mixture of lime and sand that may include various additives to improve its strength, durability and color. These could include animal hair for strength, shells as an aggregate, and natural pigments added for color. An appropriate lime-based mortar is vital to a church’s historic brick construction. The lime mortar is softer than the brick and when structural movement occurs, the lime mortar is more flexible and forgiving. Therefore, when cracking occurs it will generally happen along the mortar joints, as opposed to in the bricks themselves. The advantage being that it is much easier to repair the mortar joints than replace bricks. Unacceptable modern treatments that include the use of Portland cement (a fast-setting concrete) are disastrous to the older, softer bricks. The addition of Portland in the mortar mix can greatly diminish the integrity of the masonry by slowly crushing the bricks during natural cycles of expansion and contraction. The rigid Portland cement then causes the face of the brick to crumble and fall away, known as “spalling.”</p>
<p>Remember that in dealing with historic brick, it is normal for the mortar to eventually develop cracks, become loose and fall out, creating gaps around the brick. This is considered to be normal and only means that the mortar has outlived its life cycle. Hire a mason knowledgeable about historic brick to restore your masonry in a process known as repointing.</p>
<p><big><b>Proper maintenance and repair of Church Masonry & Stucco</b></big></p>
<p>Here are some simple tips to help preserve your church brick, stucco and masonry:</p>
<p>1. Inspection of your church masonry should be performed by experienced masons on a regular basis.</p>
<p>2. Maintenance and repairs should be made in a timely fashion. Delays in simple maintenance frequently result in costly repairs.</p>
<p>3. Direct water away from bricks. Bricks and lime based mortar are essentially porous and when they’re exposed to prolonged saturation, deterioration may occur. Quickly repair any leaks from the church gutters and roofs. You should also redirect any water that pools around the building foundation.</p>
<p>4. Vegetation should not be permitted to grow on any masonry, nor too close to your foundation. Both the roots and moisture may cause masonry damage. (This can also be inviting to termites and other insects.)</p>
<p>5. Never use harsh cleaning methods, such as sandblasting or power washing. These techniques can actually strip the hardened outer face of the brick and weaken its integrity.</p>
<p>6. Water sealants, paint and brick do not mix. Masonry is designed to be porous, and these treatments prevent natural wicking (absorption of water) and moisture release. If you practice the preventive maintenance outlined above, water sealants and paints are not necessary. However, if the church masonry has been painted or treated careful expert evaluation should be consulted to determine the best course of action.</p>
<p>We are nationwide stone masons, tuck pointers and stone restorationists that offer specialized church and church steeple maintenance, repair and restoration services in Alabama, Alaska, Arizona, Arkansas, California, Colorado, Connecticut, Delaware, Florida, Georgia, Hawaii, Idaho, Illinois, Indiana, Iowa, Kansas, Kentucky, Louisiana, Maine, Maryland, Massachusetts, Michigan, Minnesota, Mississippi, Missouri, Montana, Nebraska, Nevada, New Hampshire, New Jersey, New Mexico, New York, North Carolina, North Dakota, Ohio, Oklahoma, Oregon, Pennsylvania, Rhode Island, South Carolina, South Dakota, Tennessee, Texas, Utah, Vermont, Virginia, Washington, West Virginia, Wisconsin, Wyoming. Including the cities of New York, NY - Los Angeles, CA - Chicago, IL - Houston, TX - Philadelphia, PA - San Diego, CA - Detroit, MI - Dallas, TX - Phoenix, AZ - San Antonio, TX - San Jose, CA - Baltimore, MD - Indianapolis, IN - San Francisco, CA - Jacksonville, FL - Columbus, OH - Milwaukee, WI - Memphis, TN - Washington, DC - Boston, MA - Seattle, WA - St. Louis, MO - Atlanta, GA - Pittsburgh, PA - Minneapolis, MN - Miami, FL - Tampa, FL</p>
					<div class="clear"></div>				</div>			</div>		<div class="page_bot"></div>	</div>	<div id="footer">		<div class="botlinks"></div>		<div class="copyright">			All content copyright <strong>Inspired Heights, Inc.</strong>		</div>		<div class="clear"></div>	</div></div></body></html>