<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html xmlns="http://www.w3.org/1999/xhtml"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /><title>Mentorship Program - Christian Discipleship / Mentoring Program</title><meta name="description" content="Mentorship Program includes spiritual, occupational and life skill mentoring" /><link href="design/style.css" rel="stylesheet" type="text/css" /><script type="text/javascript" src="js/fade.js"></script></head><body><div id="wrapper">	<div id="header">		<div class="phone"></div>		<div class="logo"><a href="/" title="Inspired Heights"><img src="images/logo.png" width="270" height="50" border="0" alt="Inspired Heights" /></a></div>	</div>	<div id="nav">		<div class="navigation_menu">			<div class="navigation_tcat"></div>			<ul class="menu">				<li><a href="index.php" class="menu_home" title="Home"></a></li>				<li><a href="about.php" class="menu_abou" title="About Us"></a></li>				<li><a href="church-steeples.php" class="menu_cste" title="Church Steeples"></a></li>				<li><a href="church-roofs.php" class="menu_croo" title="Church Roofs"></a></li>				<li><a href="mason_stone-restoration.php" class="menu_mres" title="Mason/Stone Restoration"></a></li>				<li><a href="church-windows.php" class="menu_cwin" title="Church Windows"></a></li>				<li><a href="church-interiors.php" class="menu_cint" title="Church Interiors"></a></li>				<li><a href="mentorship-program.php" class="menu_mpro" title="Mentorship Program"></a></li>			</ul>		</div>		<div class="display"><script type="text/javascript" language="javascript">new fadeshow(fadeimages, 693, 299, 0, 3000, 0);</script></div>		<div class="clear"></div>	</div>	<div id="titlebar">		<h1>The Mentoring Program</h1>		<div class="contact_button"><a href="contact.php" title="Contact Us"></a></div>		<!-- <div class="portfolio_button"><a href="#" title="Project Portfolio"></a></div> -->		<div class="clear"></div>	</div>	<div id="page">		<div class="page_top"></div>			<div class="page_main">				<div class="page_wrap">					<div class="float_right"><img src="images/mentorship_program.jpg" border="0" alt="Mentorship Program" /></div>
<p>Inspired Heights is now offering a mentorship program to help ex-offenders "rise" to new heights... Inspired Heights!</p>
<h1>Occupational</h1>
<p>The occupational mentoring consists of general job skill training and specialized training in the construction trades. These may include roofing, carpentry, painting, stone restoration, sheet metal work, tuck pointing, and more. The specific trades available will be determined by the current projects and the participant's aptitude.</p>
<h1>Life Skills</h1>
<p>The mentoring program also addresses other areas of life necessary to live productive, overcoming lives. Such topics include addiction recovery, anger management, life after incarceration, and financial discipline. The studies are discussed as part of a discipleship class that participants must attend.</p>
<h1>Spirit</h1>
<p>Every element of Inspired Height's mentoring program incorporates the Christian life. The participants are taught and expected to work, study, and live according to Biblical principles. Every morning begins with prayer and Bible study and it is required for everyone to attend a Bible believing Christian church at least twice a week.</p>
<h1>Restoring Churches while God restores lives!</h1>
<p><em>He who has been stealing must steal no longer, but must work, doing something useful with his own hands, that he may have something to share with those in need. -- Ephesians 4:28</em></p>
					<div class="clear"></div>				</div>			</div>		<div class="page_bot"></div>	</div>	<div id="footer">		<div class="botlinks"></div>		<div class="copyright">			All content copyright <strong>Inspired Heights, Inc.</strong>		</div>		<div class="clear"></div>	</div></div></body></html>